#!/usr/bin/env python3
"""
Test translation of English hints to Finnish.

Takes the English hints generated by llama3.2:3b BALANCED strategy
and translates them to Finnish while ensuring the quiz word isn't used.
"""

import requests
import json
import time

OLLAMA_HOST = "172.23.64.1"
OLLAMA_PORT = 11434
MODEL = "llama3.2:3b"

# English hints from llama3.2:3b BALANCED strategy (from terminal output)
TEST_CASES = [
    {
        'english_word': 'dog',
        'finnish_word': 'koira',
        'hints': [
            "1. A loyal companion that often accompanies its owner on a daily walk.",
            "2. Frequently found at outdoor events, such as festivals and parades.",
            "3. Typically has a distinctive odor and shedding fur."
        ]
    },
    {
        'english_word': 'house',
        'finnish_word': 'talo',
        'hints': [
            "1. A place where family gatherings and holidays take place, often decorated with festive lights.",
            "2. Typically has four walls, a roof, and doors that open to reveal a private space for sleeping and relaxation.",
            "3. Found on many city streets, its entrance is usually marked by a mailbox or a front door."
        ]
    },
    {
        'english_word': 'red',
        'finnish_word': 'punainen',
        'hints': [
            "1. A vibrant color often associated with roses and apples.",
            "2. The fiery hue of a sunset on a summer evening.",
            "3. A deep, bold tone reminiscent of a Valentine's Day heart symbol."
        ]
    },
    {
        'english_word': 'to eat',
        'finnish_word': 'syödä',
        'hints': [
            "1. I'm often done with a spoon, and I can be messy.",
            "2. In some cultures, it's a social ritual where food is shared from a central plate.",
            "3. A bodily function necessary for survival"
        ]
    }
]


def preload_model(model_name):
    """Preload the model by making a simple request to warm it up."""
    print(f"🔄 Preloading {model_name}...")
    try:
        payload = {"model": model_name}
        result = requests.post(f"http://{OLLAMA_HOST}:{OLLAMA_PORT}/api/chat", json=payload, timeout=480).json()
        load_time = result.get("load_duration", 0) / 1e9
        print(f"✓ {model_name} loaded ({load_time:.1f}s)" if load_time > 0 else f"✓ {model_name} already loaded")
    except Exception as e:
        print(f"⚠ Preload failed: {e}")


def clear_chat_context(model_name):
    """Clear the chat context by sending an empty request."""
    url = f"http://{OLLAMA_HOST}:{OLLAMA_PORT}/api/chat"
    payload = {
        "model": model_name,
        "messages": [{"role": "user", "content": "clear"}],
        "stream": False
    }
    try:
        requests.post(url, json=payload, timeout=30)
    except:
        pass  # Ignore errors


def translate_hints(test_case):
    """Translate English hints to Finnish while preserving format and avoiding the quiz word."""
    english_word = test_case['english_word']
    finnish_word = test_case['finnish_word']
    hints_text = '\n'.join(test_case['hints'])
    
    print(f"→ Translating hints for '{english_word}' to Finnish...")
    url = f"http://{OLLAMA_HOST}:{OLLAMA_PORT}/api/chat"
    
    system_prompt = f"""You are a professional translator specializing in quiz hint translation from English to Finnish.

CRITICAL TRANSLATION RULES:
- Translate the following hints from English to Finnish
- NEVER use the Finnish word "{finnish_word}" in any of the translated hints
- Do NOT use any part of the word "{finnish_word}"
- Do NOT use synonyms of "{finnish_word}" in Finnish
- Maintain the same format as the original: numbered hints (1., 2., 3.)
- Keep the same level of detail and difficulty as the original
- Preserve the structure: each hint should remain on a single line
- Translate naturally while keeping the clues accurate

OUTPUT FORMAT:
Output exactly three numbered lines in Finnish, nothing else.
Each line should start with the number (1., 2., 3.) followed by the translated hint.
Example format:
1. [Finnish translation of first hint]
2. [Finnish translation of second hint]
3. [Finnish translation of third hint]"""

    user_prompt = f"""Translate these English hints to Finnish:

{hints_text}

CRITICAL: Do NOT use the word "{finnish_word}" or any of its forms in your Finnish translation.
The quiz word "{english_word}" (Finnish: "{finnish_word}") must NOT appear in the translated hints."""
    
    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "stream": False,
        "options": {"temperature": 0.5}  # Lower temperature for more consistent translation
    }
    
    try:
        response = requests.post(url, json=payload, timeout=180)
        response.raise_for_status()
        
        result = response.json()
        
        # Extract timing
        total_duration = result.get("total_duration", 0) / 1e9
        eval_count = result.get("eval_count", 0)
        
        # Get content
        message = result.get("message", {})
        content = message.get("content", "").strip()
        
        return {
            "success": bool(content),
            "translation": content,
            "duration": total_duration,
            "tokens": eval_count
        }
        
    except requests.exceptions.Timeout:
        return {"success": False, "translation": "", "duration": 0, "tokens": 0, "error": "Timeout"}
    except Exception as e:
        return {"success": False, "translation": "", "duration": 0, "tokens": 0, "error": str(e)}


def validate_translation(translation, forbidden_word):
    """Check if the forbidden word appears in the translation."""
    translation_lower = translation.lower()
    forbidden_lower = forbidden_word.lower()
    
    # Check for the exact word
    if forbidden_lower in translation_lower:
        return False, f"❌ Contains forbidden word '{forbidden_word}'"
    
    # Check for common Finnish word forms (basic check)
    # For example, "koira" -> "koiran", "koiraa", "koiralla", etc.
    base_forms = [
        forbidden_lower + 'n',  # genitive
        forbidden_lower + 'a',  # partitive
        forbidden_lower + 'lla', # adessive
        forbidden_lower + 'lle', # allative
        forbidden_lower + 't',  # plural nominative
    ]
    
    for form in base_forms:
        if form in translation_lower:
            return False, f"❌ Contains forbidden word form '{form}'"
    
    return True, "✓ No forbidden words detected"


def check_format(translation):
    """Check if the translation follows the expected format."""
    lines = translation.strip().split('\n')
    
    # Should have exactly 3 lines
    if len(lines) != 3:
        return False, f"❌ Expected 3 lines, got {len(lines)}"
    
    # Each line should start with number
    for i, line in enumerate(lines, 1):
        if not line.strip().startswith(f"{i}."):
            return False, f"❌ Line {i} doesn't start with '{i}.'"
    
    return True, "✓ Format correct"


def main():
    print("=" * 80)
    print("FINNISH TRANSLATION TEST")
    print("=" * 80)
    print(f"\nTranslating English hints to Finnish using model: {MODEL}")
    print("Ensuring quiz words are not used in translations\n")
    
    # Test connection
    print("🔌 Testing connection...")
    try:
        resp = requests.get(f"http://{OLLAMA_HOST}:{OLLAMA_PORT}/api/version", timeout=180)
        version = resp.json().get("version", "unknown")
        print(f"✓ Connected to Ollama v{version}")
    except Exception as e:
        print(f"✗ Failed: {e}")
        return
    
    # Preload model
    print()
    preload_model(MODEL)
    print()
    
    # Process each test case
    results = []
    total_duration = 0
    total_tokens = 0
    
    for i, test_case in enumerate(TEST_CASES, 1):
        print(f"\n{'='*80}")
        print(f"TEST CASE {i}: {test_case['english_word']} → {test_case['finnish_word']}")
        print(f"{'='*80}")
        
        print("\nOriginal English hints:")
        for hint in test_case['hints']:
            print(f"  {hint}")
        
        # Clear context before each request
        clear_chat_context(MODEL)
        time.sleep(0.5)
        
        # Translate
        result = translate_hints(test_case)
        
        if result["success"]:
            print(f"\n⏱️  Duration: {result['duration']:.1f}s | 🪙 Tokens: {result['tokens']}")
            print(f"\n📝 Finnish translation:")
            print(result["translation"])
            
            # Validate
            print(f"\n🔍 Validation:")
            word_check, word_msg = validate_translation(result["translation"], test_case['finnish_word'])
            format_check, format_msg = check_format(result["translation"])
            
            print(f"  {word_msg}")
            print(f"  {format_msg}")
            
            results.append({
                "test_case": test_case,
                "result": result,
                "word_check": word_check,
                "format_check": format_check
            })
            
            total_duration += result["duration"]
            total_tokens += result["tokens"]
        else:
            error = result.get("error", "Unknown error")
            print(f"\n✗ FAILED: {error}")
            results.append({
                "test_case": test_case,
                "result": result,
                "word_check": False,
                "format_check": False
            })
    
    # Print summary
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    
    successful = sum(1 for r in results if r["result"]["success"])
    word_violations = sum(1 for r in results if not r["word_check"])
    format_issues = sum(1 for r in results if not r["format_check"])
    
    print(f"\nTotal test cases: {len(TEST_CASES)}")
    print(f"Successful translations: {successful}/{len(TEST_CASES)}")
    print(f"Word violations: {word_violations}")
    print(f"Format issues: {format_issues}")
    print(f"\nTotal duration: {total_duration:.1f}s")
    print(f"Average duration: {total_duration/len(TEST_CASES):.1f}s per translation")
    print(f"Total tokens: {total_tokens}")
    print(f"Average tokens: {total_tokens/len(TEST_CASES):.0f} per translation")
    
    if word_violations == 0 and format_issues == 0 and successful == len(TEST_CASES):
        print("\n✅ ALL TESTS PASSED!")
    else:
        print("\n⚠️  Some tests had issues")
    
    print("\n" + "=" * 80)


if __name__ == "__main__":
    main()

